---

- hosts: all
  become: true
  tasks:

  - name: Updating repository index
    apt:
      update_cache: yes

  - name: Installing apache2 package
    apt:
      name: apache2

  - name: Adding PHP support for apache
    apt:
      name: libapache2-mod-php

